
INSERT INTO raza(nombre) VALUES ('Akita');
INSERT INTO raza(nombre) VALUES ('Alaskan Malamute');
INSERT INTO raza(nombre) VALUES ('Bichón');
INSERT INTO raza(nombre) VALUES ('Bobtail ');
INSERT INTO raza(nombre) VALUES ('Boston Terrier');
INSERT INTO raza(nombre) VALUES ('Boxer');
INSERT INTO raza(nombre) VALUES ('Bull Terrier');
INSERT INTO raza(nombre) VALUES ('Bulldog');
INSERT INTO raza(nombre) VALUES ('Chihuahua');
INSERT INTO raza(nombre) VALUES ('Cocker');
INSERT INTO raza(nombre) VALUES ('Dálmata');
INSERT INTO raza(nombre) VALUES ('Dóberman');



INSERT INTO distrito(nombre) VALUES ('Breña');
INSERT INTO distrito(nombre) VALUES ('Carabayllo');
INSERT INTO distrito(nombre) VALUES ('Chaclacayo');
INSERT INTO distrito(nombre) VALUES ('Chorrillos');
INSERT INTO distrito(nombre) VALUES ('Cieneguilla');
INSERT INTO distrito(nombre) VALUES ('Comas');
INSERT INTO distrito(nombre) VALUES ('El Agustino');
INSERT INTO distrito(nombre) VALUES ('Independencia');
INSERT INTO distrito(nombre) VALUES ('Jesús María');
INSERT INTO distrito(nombre) VALUES ('La Molina');
INSERT INTO distrito(nombre) VALUES ('La Victoria');
INSERT INTO distrito(nombre) VALUES ('Lima');
INSERT INTO distrito(nombre) VALUES ('Lince');
INSERT INTO distrito(nombre) VALUES ('Los Olivos');
INSERT INTO distrito(nombre) VALUES ('Lurigancho');
INSERT INTO distrito(nombre) VALUES ('Lurín');
INSERT INTO distrito(nombre) VALUES ('Magdalena del Mar');
INSERT INTO distrito(nombre) VALUES ('Miraflores');
INSERT INTO distrito(nombre) VALUES ('Pachacamac');
INSERT INTO distrito(nombre) VALUES ('Pucusana');
INSERT INTO distrito(nombre) VALUES ('Pueblo Libre');
INSERT INTO distrito(nombre) VALUES ('Puente Piedra');
INSERT INTO distrito(nombre) VALUES ('Punta Hermosa');
INSERT INTO distrito(nombre) VALUES ('Punta Negra');
INSERT INTO distrito(nombre) VALUES ('Rimac');
INSERT INTO distrito(nombre) VALUES ('San Bartolo');
INSERT INTO distrito(nombre) VALUES ('San Borja');
INSERT INTO distrito(nombre) VALUES ('San Isidro');
INSERT INTO distrito(nombre) VALUES ('San Juan de Lurigancho');
INSERT INTO distrito(nombre) VALUES ('San Juan de Miraflores');
INSERT INTO distrito(nombre) VALUES ('San Luis');
INSERT INTO distrito(nombre) VALUES ('San Martín de Porres');
INSERT INTO distrito(nombre) VALUES ('San Miguel');
INSERT INTO distrito(nombre) VALUES ('Santa Anita');
INSERT INTO distrito(nombre) VALUES ('Santa María del Mar');
INSERT INTO distrito(nombre) VALUES ('Santa Rosa');
INSERT INTO distrito(nombre) VALUES ('Santiago de Surco');
INSERT INTO distrito(nombre) VALUES ('Surquillo');
INSERT INTO distrito(nombre) VALUES ('Villa El Salvador');
INSERT INTO distrito(nombre) VALUES ('Villa María del Triunfo');

INSERT INTO dueno(apellido, contrasena, correo, direccion, fechadenacimiento, nombre, iddistrito)VALUES ('Parvina', '123', 'maria@gmail.com', 'Los claveles', '12/08/1990', 'Maria', 1);
INSERT INTO dueno(apellido, contrasena, correo, direccion, fechadenacimiento, nombre, iddistrito)VALUES ('Prado', '456', 'juan@gmail.com', 'el tambo', '01/08/1980', 'Juan', 5);
INSERT INTO dueno(apellido, contrasena, correo, direccion, fechadenacimiento, nombre, iddistrito)VALUES ('Chavez', '159', 'Pablo@gmail.com', 'N°123', '08/10/1987', 'Pablo', 1);
INSERT INTO dueno(apellido, contrasena, correo, direccion, fechadenacimiento, nombre, iddistrito)VALUES ('Rosales', '753', 'Miriam@gmail.com', 'las hormigas N° 147', '15/04/1989', 'Miriam', 11);
